# This is a basic workflow to help you get started with Actions

name: Release

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Unit tests
        run: npm run test

      - name: Git tag
        run: |
          export UIKIT_VERSION=$(cat ./package.json | jq '.version' | sed -e 's/"//' -e 's/"//')
          git tag ${UIKIT_VERSION}
          git push https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@github.com/hlminh2000/argo-uikit --tags
